= Bug of the day

The raspberry pi 3 port started having flaky behaviour in page table cloning
code, which looked like this:

[source, cpp]
----
LOG("Clone");
auto table_page = palloc.allocate(1);
if (!table_page) {
    return unexpected(mmu_errors::page_alloc_fail);
}

EXPECTED_TRYV(allocate_region(
    get_current_translation_table(),
    {{reinterpret_cast<uint64_t>(palloc.address_of(*table_page)), 4096},
     permissions::read_write},
    user_accessible::no,
    &palloc));

EXPECTED_TRYV(
    mark_resident(get_current_translation_table(),
                  {{reinterpret_cast<uint64_t>(palloc.address_of(*table_page)), 4096},
                   permissions::read_write},
                  memory_types::normal,
                  palloc.address_of(*table_page)));

auto table_ptr = new (palloc.address_of(*table_page)) translation_table;
*table_ptr = existing;
----

"Clone" would be logged but nothing else was coming out. Turns out we were having a
data abort after that log.

I observed placing log statements at every empty line fixed the issue. Great! We have
a timing issue.

However, timing issues mostly occur when interfacing with hardware or in concurrent
stuff, but this piece of code belongs to neither category. It only does normal memory
changes. Or does it?

Nope! Both the `allocate_region` and `mark_resident` calls operate on the current memory
map. In other words they effectively talk to the MMU, i.e. hardware.

The fix was to place barriers before we accessed the newly mapped pages.