= Writing Tests
fatih

This document explains how to write unit tests that can be run on a development machine.

For writing unit tests, we use the link:https://github.com/onqtam/doctest[`doctest`] testing framework for now, though it's possible to replace this with something we write that can run on embedded devices too as doctest can't run due to some features it requires.

== Run the existing tests

Before writing your first test, you should get yourself familiar with _how_ to run tests. Tests run on a development machine (and a dedicated build machine for every commit). They still run in a tos environment, so the test code can assume the threading model and the library environment, but can't depend on device code or test them.

To run tests, first build tos with tests enabled for `x86/hosted` CPU. As we're not targeting an embedded device, and to make debugging easier, we can actually generate normal Debug binaries:

[source, sh]
----
mkdir build-debug
cmake -DTOS_CPU=x86/hosted -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
----

Tests for the general stuff live in the `tests` folder in the root directory, so we can start there:

[source, sh]
----
cd tests
make -j4
ctest
----

This should give you something like this:

[source, sh]
----
Running tests...
Test project /home/fatih/tos/cmake-build-debug/tests
...
      Start 11: io_tests
11/11 Test #11: io_tests .........................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 11

Total Test time (real) =   5.77 sec
----

Note that you must build the tests before you can run them. If you just say `make test`, it **won't** attempt to build them first and either fail because it can't find the test binaries or it will run stale tests. So make sure you build the tests before running `make test`. You can run individual tests by running their executable.

== Creating a test file

First, find a place to place your test. You can place them in the root `tests` directory, but prefer placing them as close to the stuff it's testing as possible. This may make running all tests more difficult, but it makes finding the source of a break easier. You can create a tests directory in the feature's directory too.

Then, create a file like `<Name of the thing being tested>_test.cpp` with the following content:

[source,cpp]
----
#include <doctest.h>

namespace <Namespace of the feature> {
namespace {
// Your test contents here
}
}
----

IMPORTANT: Place everything you write in a test in an anonymous namespace to prevent colliding with other tests in case we link the tests together.

Then, edit the `CMakeLists.txt` file by adding the following lines to build your test if tests are enabled:

[source,cmake]
----
if (BUILD_TESTS)
    add_executable(<Test name>_test <Test name>_test.cpp)
    target_link_libraries(<Test name>_test PUBLIC tests_main [your stuff here])
    add_test(NAME <Test name>_test COMMAND <Test name>_test)
endif()
----

If you have a separate tests directory, put the body of the `if` directly in the CMakeLists.txt of that directory, and put the `add_subdirectory` directive in the if:

[source,cmake]
----
if (BUILD_TESTS)
    add_subdirectory(tests)
endif()
----

== Writing your unit tests

With your file in place, you're ready to write your own unit tests!

A test case looks like this:

[source,cpp]
----
TEST_CASE("Name of the test") {
    int x = 3;
    int y = 5;
    REQUIRE(x > 0);
    REQUIRE_NE(x, y);
    REQUIRE_EQ(8, x + y);
}
----

TIP: Only use the raw `REQUIRE` macro for testing something for boolean `true`. If you need to require that two things are equal, use `REQUIRE_EQ(left, right);` instead of `REQUIRE(left == right);`. Place the expected value on the left hand side in such expressions. Doctest prints the value on the left as the expected and the one on the right as the one provided. For instance, `REQUIRE_EQ(3.14, compute_pi());`.

You can check the existing tests or look at the doctest documentation for more information.