= Hosted Drivers

Tos is able to work in a process in a hosted environment such as
Linux or MacOS.

In such a case, this driver set provides best effort emulations of
real world hardware such as networking, serial communication, timers
and displays.

Currently, most of the functionality is built on top of boost asio,
and requires a boost installation. Boost is not included in the
monorepo and needs to be installed separately.

Display emulation uses X11 directly and is not extremely portable.
Other backends can be added in the future.

These drivers do not contain any machine specific code, and can run
on any architecture.

One notable issue is that the timers do not support getting the
current counter and the period (since asio does not expose that
information). This means that you cannot construct a `tos::clock`
from an hosted timer. For this reason, the hosted driver set
provides wrappers for C++ chrono clocks to be used as tos clocks.

== Details:

. <<display.adoc#, Display emulator>>