= Ambience

Ambience is an operating system for the Internet of Things.

It's like a https://en.wikipedia.org/wiki/Unikernel[unikernel]. A unikernel is *compiled with its applications* to form *one image* to be run on a machine. To compile Ambience, a deployment must be provided too, which describes where each application (i.e. service) will run. Ambience is *compiled with its applications and deployment* to form *at least one image*.

The key abstraction in Ambience is the *service*. A service comprises an interface and implementation. The programmer writes the interface in a custom IDL: lidl, and usually writes the implementation in C++ . He/she can move a service across machines or address spaces (i.e. isolation groups) with a simple change to the deployment. This is a facility not provided by other operating systems.

Services often issue requests to dependent services, which Ambience optimizes novelly. For example, consider a data publishing service that depends on a data cleaning service. Ambience will compile the data publishing service so that it uses the best transport mechanism depending on the deployment. It will use one of three different mechanisms:

- If the services are on different machines, the request is sent over the network.
- If the services are on the same machine and in different address spaces, the request is sent via IPC (a protected memcpy)
- If the services are on the same machine and in the same address space, service requests compile to function calls.

Such optimizations allow Ambience to run even on very small microcontrollers.

== Getting Started

There is a helper script to document and ease setting up an Ambience build environment.

The only dependencies of the script are GNU coreutils, `bash`, `sed`, and `dnf`, the Fedora package manager. The only tested `dnf` version is 4.5.2.

To build, run, and test the `calc_test_deployment`, run these commands as root:

[source,bash]
----
wget https://raw.githubusercontent.com/MAYHEM-Lab/ambience/master/scripts/ambience-helpers.sh
chmod +x ambience-helpers.sh
mkdir build-env-directory
./ambience-helpers.sh bootstrap build-env-directory
./ambience-helpers.sh setup build-env-directory
./ambience-helpers.sh run-and-query-basic-calc build-env-directory
----

The final line should print `SUCCESS`.

You may use `/` for `build-env-directory` on a Fedora 36 machine to set up the machine for development. Otherwise, you must chrooted into `build-env-directory` to do anything.

== Other Resources

- Ambience paper: link TODO
- Benchmarking paper comparing Ambience to other systems: https://sites.cs.ucsb.edu/~ckrintz/papers/bench22.pdf
  - Presentation from that conference: https://www.youtube.com/watch?v=IKR8mt1ZRdQ
- Class presentation on Ambience and its helper script: https://www.youtube.com/watch?v=Fa61fc1_flk
- Tutorial on creating a new Ambience service: <<docs/ToolchainNotes#>>

