= Intrusive lists

== Motivation

**The** data structure of an operating system is a linked list. They are used for maintaining the list of 
runnable threads, threads blocked on a mutex, packets received by a network interface etc.

While C++ provides `std::list`, it's not fit for use in most of our applications as it owns and allocates
its individual elements. It's a fine container. It can carry pretty much _any_ type: ints, strings, pointers,
user defined types etc. It is completely non-intrusive.

However, this flexibility comes at a cost. A run queue doesn't own its elements, once a thread is taken off
the run-queue, it doesn't get deallocated. Therefore, you'd need to store pointers in your list instead of 
the elements themselves. Considering a list element will contain 2 more pointers for next and previous siblings
of the node, for each element in a list, we'll be allocating 3 pointers + heap overhead. On top of the size 
overhead, allocations are often slow and things go in and out of lists all the time, compounding the issue.
This clearly is not desireable.

Also, we know that our threads will, most of the time, be stored in lists. We can take advantage of this by
modifying our thread control block structure to contain 2 pointers (next and previous) all the time. This way,
no allocation will be needed to place an element in a list, just 2 pointer adjustments.

== `tos::intrusive_list`

Tos provides an intrusive list template, and its straightforward to use.

Quick example use:

[code, cpp]
----
#include <tos/intrusive_list.hpp>
#include <string>

struct my_type : tos::list_node<my_type> {
    std::string name;
};

tos::intrusive_list<my_type> some_list;

void foo() {
    my_type x;
    x.name = "foobar";
    auto iter = some_list.push_back(x);
    
    // do something, possibly block
    
    // Don't forget to remove your element from a list before it's destructed!
    some_list.erase(iter);
}
----

=== Use with element-wise synchronization

[code, cpp]
----
#include <tos/intrusive_list.hpp>
#include <tos/semaphore.hpp>
#include <string>

struct my_type : tos::list_node<my_type> {
    std::string name;
    tos::semaphore sem{0};
};

tos::intrusive_list<my_type> some_list;

void foo() {
    my_type x;
    x.name = "foobar";
    auto iter = some_list.push_back(x);
    
    x.sem.down(); // Some other thread will up us, and we'll take ourselves off the list.
    
    // Don't forget to remove your element from a list before it's destructed!
    some_list.erase(iter);
}
----
