= Callbacks in C++
fatih

## Callbacks under the hood

In C++ code, when passing a callback, you have 3 options:

. The callback is called immediately from the function.
. The callback is stored and the lifetime is managed by the caller.
. The callback is stored and the lifetime is managed by the callee.

For the first case, prefer using a template parameter to take the function:

[source,cpp]
----
template <class FuncT>
void call_100_times(const FuncT& func) {
  for (int i = 0; i < 100; ++i) func();
}

call_100_times([] {
  // do something
});
----

This has absolutely no overhead, and can be used without a thought.

The downsides of this approach is that it contains no information whatsoever in the interface
so the callers have no idea about what kind of a function they should pass. This must be clarified
in the comments, and if possible, checked with a `static_assert`.

---

For the second case, use `tos::function_ref`. It's a **non-owning** function reference:

[source,cpp]
----
void call_on_interrupt(tos::function_ref<void()> fn) {
  global_int_handler = fn; // free to copy!
}

// Does not work!
call_on_interrupt([]{
  // do something
});

auto int_handler = []{
  // do something
};

// Still does not work!
// The constructor is explicit
call_on_interrupt(int_handler);

// Great!
call_on_interrupt(tos::function_ref<void()>(int_handler));
----

The things to note here are:

. You can't pass a temporary function (like a lambda) to the function since the function would
be dead by the time the function returns. So the function object must have a name, and it **MUST**
live longer than the duration the caller will call it.
. You can't implicitly create a `tos::function_ref` even from a named function to ensure the caller
knows that there's a reference is taken to this function.

Other than these, it's obvious from the signature what the arguments to the expected function is
so the callers can immediately see what kind of a function they should return.

There's no allocation going on so it's allowed almost everywhere in the codebase. One issue is that
as this is an indirect call, the stack analysis can no longer determine how much stack a particular
code path uses when a `function_ref` is involved, so it's use should be limited.

Calling it is not as cheap as the template case, but it's one indirect call, so it's not that bad.

---

For the third case, you're pretty much out of luck. tos provides `std::function` in the standard
library, but it allocates and doesn't take an allocator, so it'll always use `new`, which means
it's pretty limited. It's use is prohibited unless there's a specific reason this is being done.

For completeness, here's how it looks like:

[source,cpp]
----
void call_on_interrupt(std::function<void()> fn) {
  global_int_handler = std::move(fn); // make sure you move it, as it'll allocate again on copy!
}

// OK, the constructor of std::function will copy the function to heap!
call_on_interrupt([]{
  // do something
})
----

The downsides are plenty:

. The function object must be copyable, so if it captures something move-only, you're out of luck.
. The function is copied to dynamic memory at construction, without a chance of providing an allocator.
. Calling a `std::function` at some point involves a virtual function call, which is at least 2 indirections.

---

## C Callbacks

There are 2 cases when interfacing with a C library that employs callbacks:

. It assumes everything is global, and takes only a function pointer.
. It's written by decent programmers, and the API also takes what's called a `context` or `user` pointer.

If you have a library that took the 1st option, either modify the library so it's now like the second case, or drop that library.

### Function pointers

A function pointer looks like this:

[source,cpp]
----
using fun_ptr_1 = void(*)();
using fun_ptr_2 = void(*)(int);
using fun_ptr_3 = int(*)(char);
----

. `fun_ptr_1` is a pointer type to a function that takes no arguments and returns nothing.
. `fun_ptr_2` is a pointer type to a function that takes an integer and returns nothing.
. `fun_ptr_3` is a pointer type to a function that takes a char and returns and integer.

That is, if you're using C++. With C, we have to resort to `typedef`s for the same things:

[source,cpp]
----
typedef void (*fun_ptr_1)();
typedef void (*fun_ptr_2)(int);
typedef int (*fun_ptr_3)(char);
----

If you have a function that takes a callback in C, it takes a parameter of type of a function pointer:

[source,cpp]
----
void call_100_times(fun_ptr_1 fun) {
  for (int i = 0; i < 100; ++i) fun();
}
}
----

Since this is C, the only way to use this function is to define another function and pass it:

[source,cpp]
----
void call_me() {
 // do something
}

int main() {
  call_100_times(&call_me);
}
----

This is fine and all, but imagine we'd like to print a local variable 100 times:

[source,cpp]
----
int main() {
  int x = get_x();
  call_100_times(print_x???); // what to do?
}
----

The only way to print `x` is to put _something_ in a global (or thread local) variable and print
it from a regular, freestanding function. There are many reasons globals make up for horrible code,
so we'd like to avoid this global variable. The way it works is to use what's called a _context_
or _user_ pointer.

### Context pointers

A _context_ or _user_ pointer is an additional argument to any C function that takes a callback
that will be passed back to the given callback so the called function has an idea of what's going on.
This means that the function pointer type is changed to take one additional pointer. The type of this
pointer must be a `void*` since `call_100_times` must be able to work with any context type:

[source,cpp]
----
using ctx_fun_ptr = void(*)(void*);
void call_100_times(ctx_fun_ptr fun, void* ctx) {
  for (int i = 0; i < 100; ++i) fun(ctx);
}

void print_an_int(void* ctx) {
  int* x = (int*)ctx; // if ctx is not actually an int* bye bye
  printf("%d\n", *x);
}

int main()
{
  int x = get_x();
  call_100_times(&print_an_int, &x);

  double y = get_y();
  call_100_times(&print_an_int, &y); // compiles, undefined behaviour!
}
----

### Interfacing C libraries from C++

As C is not a supported language in C, C code can only live in leaf libraries. Luckily C++ can
speak C without an issue. When using C++, implement the callback functions as regular class
members, pass `this` as the context pointer and use a lambda that will marshall the context back
to `this` and call the handler:

[source,cpp]
----
class int_printer {
public:
  int_printer(int x) : print_what(x) {}

  void print() {
    call_100_times([](void* ctx) {
      auto self_ptr = static_cast<int_printer*>(ctx);
      self_ptr->handle_callback();
    }, this);
  }

  void handle_callback() {
    std::cout << print_what << '\n';
  }

private:
  int print_what;
}

int main()
{
  int x = get_x();
  int_printer printer(x);
  printer.print();
}
----

This is obviously a convoluted example, but in general, when writing drivers using SDKs provided
by vendors, you'll have to route a callback to a class object, and this is how it's achieved.

It's important to note that if the C library doesn't call the function directly, but rather stores
it in some global or dynamic memory and later calls it, the object must still be alive!