set(TOS_CORE stm32_hal)
set(TOS_DRIVERS stm32_hal)
SET(LIBOPENCM_DEF STM32F7)
SET(TOS_CPU_ARCH cortex-m7)
set(TOS_DEF_STACK 1024)
set(TOS_TOOLCHAIN stm32Toolchain)
set(HAL_NAME stm32f7xx)
set(COMPILE_FLAGS "-mfloat-abi=hard -mfpu=fpv5-sp-d16")