version: 2
jobs:
  x86_build:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Update apt
          command: apt-get update
      - run:
          name: Install Toolchain
          command: apt-get install -y g++-7 cmake ninja-build
      - run:
          environment:
            CXX: g++-7
          name: Generate Project
          command: mkdir build && cd build && cmake -G Ninja -DTOS_X86=ON ..
      - run:
          working_directory: build/
          name: Build Project
          command: ninja
  avr_build:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Update apt
          command: apt-get update
      - run:
          name: Install Toolchain
          command: apt-get install -y gcc-avr cmake ninja-build avr-libc
      - run:
          environment:
            CXX: avr-g++
            CC: avr-gcc
          name: Generate Project
          command: mkdir build && cd build && cmake -G Ninja -DTOS_AVR=ON .. && cmake ..
      - run:
          working_directory: build/
          name: Build Project
          command: ninja
workflows:
  version: 2
  all_platforms:
    jobs:
      - x86_build
      - avr_build
