version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Install Toolchain
          command: apt-get install g++-7 cmake ninja
      - run:
          name: Generate Project
          command: mkdir build && cd build && cmake ..
