version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Update apt
          command: apt-get update
      - run:
          name: Install Toolchain
          command: apt-get install -y g++-7 cmake ninja-build
      - run:
          name: Generate Project
          command: mkdir build && cd build && cmake -DTOS_X86=ON ..
      - run:
          name: Build Project
          command: ninja
