= Porting lwIP to Tos

This document outlines the steps it took to port lwIP to tos.

== Get the source in tos

Third party code that's expected to be updated is placed in
`/third_party/LIBNAME/src`. The src directory should contain the
(preferably) unmodified sources of the library. The LIBNAME
directory will contain any necessary CMake or tos integrations
and maybe patches.

Use subtree to add an existing git repo to tos:

[source,sh]
----
git subtree add \
    --prefix=third_party/lwIP/src \
    https://git.savannah.nongnu.org/git/lwip.git \
    STABLE-2_1_2_RELEASE \
    --squash
----

We don't want to clone some random commit, so we pick the latest
stable tag.

We also don't want the entire lwIP history in tos, so we squash.

That's it!

Commit `d6504a13ee75b2a064f251062bb5d072fb08fb7c` shows this
step.

== Integrate with CMake

It looks like there's a CMakeLists.txt in lwip!

Hopefully it will build directly without any effort on our side.

To get it into tos build tree, add a new CMakeLists.txt in
third_party/lwip and add the src directory as a subdirectory:

[source,cmake]
----
add_subdirectory(src)
----

Also add the lwIP directory in third_party cmake:

[source,cmake]
----
add_subdirectory(lwIP)
----

Sadly, building it out of the box did not work:

[source,sh]
----
$ ninja lwipcore
[1/85] Building C object third_party/lwIP/src/CMakeFiles/lwipcore.dir/src/core/pbuf.c.o
FAILED: third_party/lwIP/src/CMakeFiles/lwipcore.dir/src/core/pbuf.c.o
/usr/bin/cc   -Wall -Wextra -Wpedantic      -ffunction-sections -fdata-sections -ffreestanding -g -pedantic      -Wno-unknown-pragmas -fdiagnostics-color=always -fdump-ipa-cgraph -fstack-usage -freorder-functions -U__STRICT_ANSI__ -g -MD -MT third_party/lwIP/src/CMakeFiles/lwipcore.dir/src/core/pbuf.c.o -MF third_party/lwIP/src/CMakeFiles/lwipcore.dir/src/core/pbuf.c.o.d -o third_party/lwIP/src/CMakeFiles/lwipcore.dir/src/core/pbuf.c.o   -c ../third_party/lwIP/src/src/core/pbuf.c
../third_party/lwIP/src/src/core/pbuf.c:71:10: fatal error: lwip/opt.h: No such file or directory
 #include "lwip/opt.h"
          ^~~~~~~~~~~~
----

Looks like we will have to provide some port config.

I found these resources to help:

. https://www.lse.epita.fr/lse-summer-week-2014/slides/lse-summer-week-2014-21-Porting%20and%20testing%20a%20TCPIP%20stack%20without%20an%20ethernet%20driver.pdf
. https://lwip.fandom.com/wiki/Porting_For_Bare_Metal

Turns out lwip doesn't know about it's own include dirs, so we
need to set a CMake variable to let it know:

[source,cmake]
----
set(LWIP_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/src/src/include)
----

Commit `73e54e847180d80349b691d6f055f6465386e88f` shows this.

With this change, our error becomes this:

[source,sh]
----
../third_party/lwIP/src/src/include/lwip/opt.h:51:10: fatal error: lwipopts.h: No such file or directory
 #include "lwipopts.h"
----

Great! From the documents above, we see that we need to provide
`lwipopts.h` and `arch/cc.h`.

We will create these files, but we don't want to modify the upstream
lwIP for easy upgrades in the future.

We will create an include directory in `/third_party/lwIP` and put
them here. We'll probably need some support functions anyway, so
we'll go ahead and create an `lwip_support` library and add the
include dir as it's public include directory:

[source,cmake]
----
add_library(lwip_support "")
target_sources(lwip_support PRIVATE
    support.cpp
    include/lwipopts.h
    include/arch/cc.h)
target_include_directories(lwip_support PUBLIC include)
----

To let lwIP know about this directory,  we'll just link the support
library to `lwipcore`:

[source,cmake]
----
target_link_libraries(lwipcore PUBLIC lwip_support)
----

This is possible after CMake 3.13, which we are on.

With these, `lwipcore` target builds! We're probably still missing
a bunch of stuff and it won't link, but it's a great step!

Commit `6b7e7d123c5296a921f6799cb60677dca5601216` shows these
changes.

== Making it work

After some configuration, the library