= Device Commissioning

Commissioning is the term used to describe the process to bring a device to working condition.

The primary step in the process is writing the desired program to a physical device's program memory.

== JTAG / SWD Programming

SWD is basically a lite-JTAG over fewer number of wires.

During development, the preferred programming method is writing the program to device flash over JTAG.
The upsides of JTAG programming are as follows:

. It is indepdendent of the current status of the device. Therefore, JTAG can be used to program even
an unresponsive device.
. It requires no cooperation of the software already on the device. This means that you don't need a
bootloader already on the device to program the device.
. JTAG allows for proper debugging too.

The downsides are as follows:

. It requires special interface hardware (JLink, STLink, CMSIS-DAP etc.) to access the JTAG interfaces.
It is often unavailable on non-development boards.

See an <<../start/stm32l4-disco#, example board's programming process>> over JTAG for specific steps.

== Serial programming

Cheap, amateur development boards (e.g. arduino, esp8266) and production boards do not have on board JTAG
hardware or even connectors.

In these cases, there's usually a fixed bootloader program on the device that runs first upon boot. The
bootloader checks the serial port or some GPIO pin to see if it should receive a program and overwrite
the current program.

The serial interface can be anything: UART, USB, Ethernet or even a wireless module on UART.

The upsides are as follows:

. It's cheaper. You don't need a debug probe to program the device.
. It requires neither special software nor hardware to program them. For instance, with WebUSB, you
can program a device over a web browser.

The downsides:

. It can be less reliable, especially if the bootloader can be updated. The common solution to this
problem is that the bootloader is never updated. However, a buggy program can trivially overwrite the
bootloader anyway.
. Getting to the bootloader is not a trivial task. JTAG has special pins to reset a device, serial
programming may not have an automatic way to reset a device, often requiring a user to press a button
to get to the bootloader.
