= OpenOCD
fatih

== Setup

The openocd in ubuntu repos is quite old, so we have to build one ourselves.

There are many forks of openocd. The official mirror works well for all our ARM targets:

https://github.com/ntfreak/openocd

For instance, there are other forks of openocd for ESP32 and RISC V.

=== Building

Install the dependencies:

[source,sh]
----
$ sudo apt-get install -y make libtool pkg-config autoconf automake texinfo libusb-1.0
----
or on macos 
----
$ brew install libtool autoconf automake texinfo libusb 
----

Then configure:

----
$ ./configure
----

Then compile:

----
$ make -j8
----

The binary will be in `openocd/src/openocd`.

== Attaching to the target

Once you have `openocd` built and the target connected to your machine, you can _attach_ to it.

This step depends on the target you want to debug/program.

There are 2 parts to this debugging thing. First is your _target_, i.e. the chip you want to debug. For instance, it can be a nRF52840, an STM32L053, an ESP32 etc. The second is the _interface_, i.e. what device you use to talk with the _target_. This can be an ST-LINK or JLink.

Once you have this information you can attach to your target through your interface. For instance:

----
$ openocd -f interface/stlink.cfg -f target/stm32l0.cfg
----

You should get this:

----
... something something GPL ...
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : Unable to match requested speed 300 kHz, using 240 kHz
Info : Unable to match requested speed 300 kHz, using 240 kHz
Info : clock speed 240 kHz
Info : STLINK v2 JTAG v21 API v2 SWIM v5 VID 0x0483 PID 0x374B
Info : using stlink api v2
Info : Target voltage: 3.236364
Info : stm32l0.cpu: hardware has 4 breakpoints, 2 watchpoints
Info : Listening on port 3333 for gdb connections
----

If you're at this point, you're ready for debugging or programming.

== GDB Debugging

When you attach to a target with `openocd`, it opens a remote gdb server on the machine. The good thing is, you can attach to this server with `gdb` and debug programs on the device like a normal program, you can set up break points, you can single step etc.

The default gdb port is 3333 on openocd. To connect to it, launch up the _correct_ gdb with the correct file for the program running on the device:

----
$ /opt/x-tools/gcc-arm-none-eabi-8-2018-q4-major/bin/arm-none-eabi-gdb my_firmware
----

It's important that both the gdb and the program match the target and whatever's running on it. Once you're there, you can now connect to the gdb server provided by `openocd`:

----
(gdb) target remote localhost:3333
----

Once you do this, the target will stop running, and will be waiting for your commands.

After this point, it's standard `gdb`, go crazy.

== Other `openocd` niceties

=== Search path

As we compile our own version of `openocd`, it's not going to be able to find the correct scripts if you pass `-f target/stm32l0.cfg` to it directly. It'll either find the ones installed by the system in `/usr/share`, which it shouldn't, or it won't be able to find anything.

One solution is to give it absolute paths like `/home/foo/openocd/tcl/target/stm32l0.cfg`. That's nice, but it's a mouthful. Also, if that config file includes another file, it'll again be searched in the wrong place or won't be found.

The solution is to give `openocd` a _search path_: 

----
$ openocd -s ~/openocd/tcl -f target/stm32l0.cfg -f interface/stlink.cfg
----

=== Board files

Some boards have both the target and the interface on them. And fortunately, openocd is aware of _some_ of them. If your board is one of the lucky ones, you can just pass a board file:

----
$ openocd -s ~/openocd/tcl -f board/nordic_nrf52_dk.cfg
----

And `openocd` will just read both the interface and target from the board file.

== Troubleshooting

=== `openocd` can't reset my target!

Tos puts the targets in deep sleep mode whenever there's nothing to run. Though this is great for power conservation, it's horrible for debugging as the debugger can't talk with the processor as it's asleep!

The only solution I know of when this happens is to unplug the board, prepare your connection command and press enter as soon as you connect the board, i.e. before tos has a chance to put the processor to sleep.

Obviously, this is not scalable though. If you don't want to run into this issue, comment out the deep sleep lines in core files (`tos/src/arch/YOUR_ARCH/***_core.cpp`) and re-enable them for production unless we come up with a prettier solution.
