= Time keeping in Tos
<fatih, mfatihbakir@ucsb.edu>

Keeping track of time is an important responsibility of an operating system. This document explains how
we manage time in tos.

There are mainly 2 activities users want to perform related to time:

1. Figure out what time it is, relative to some _epoch_.
2. Get notified when a certain amount of time passes.

In tos, the first activity is performed using what's called a _clock_, and the second using an _alarm_.

If you take a look at the definitions of those, you'll see that they are templates:

[source,cpp]
----
template <class TimerT>
class alarm;

template <class TimerT>
class clock;
----

The reason for the template parameter is that for those class templates to do their work, they need
_some_ way of learning about the passage of time. Physically, this is performed by a timer hardware
provided by the platform. The job of a timer is to periodically call a function. That's it! The
interface of timers look like this:

[source,cpp]
----
class Timer
{
public:
  void set_frequency(uint32_t hertz);
  void set_callback(function_ref<void()>);
  uint32_t get_counter() const;
  uint32_t get_period() const;
  void enable();
  void disable();
};
----

Upon calling `enable`, the timer will call the function given to `set_callback` `hertz` time a second, forever.

This is pretty barebones on purpose to make writing platform dependent timer drivers easy. The portable stuff like setting timeouts or keeping track of time is handled in the aforementioned templates.

## Clocks

A _clock_ is an object that tells you the current time when you call it's `now` member. That's it!

The way it's implemented is straightforward: it counts how many _ticks_ happened so far, and how long until the next tick. Since we know the frequency of ticks, computing how much time has passed since construction is just $ticks / frequency$. A clock starts keeping track of the time at it's construction, and stops at it's destruction, there is no start/stop functionality.

The clocks provide high resolution timer readings as they do not only count how many times the underlying timer ticked, but also take the time into the current tick that passed. For instance, if the timer ticks every 100ms and we've seen 3 ticks and we are 53ms into the current tick, the `now()` function of the timer will correctly return `353ms` rather than `300ms`. It accomplishes this by using the `get_counter` and `get_period` functions of the timer.

## Alarms

An _alarm_ is an object that does something you want after a certain amount of time.

Similar to clocks, an alarm also counts ticks to do it's job, but it doesn't care about timekeeping. This means that an alarm only enables a timer when there's something to run and disables it when everything's been run. This allows tos to run in completely tickless mode, and is the preferred way of doing time-related things.

Unlike clocks, alarms only work in exact multiples of the period of the timer it uses. Therefore, if the underlying timer ticks every 10ms, you cannot set an alarm for 15ms exactly. If you do, the alarm will go of at 20ms.

The main interface to an alarm is the `set_alarm` member:

[source,cpp,indent=0]
----
include::/src/drivers/include/common/alarm.hpp[lines=63]
    ...
----

It takes a `sleeper` object which is defined as:

[source,cpp,indent=0]
----
include::/src/drivers/include/common/alarm.hpp[lines=16..28]
----

It's primary reason of existence is to provide an intrusive list of functions to be called. Each alarm user constructs one of these and passes a reference to it to an `alarm` object. The alarm object will put this `sleeper` into it's sleeper queue to call them when their time comes.

[NOTE] 
====
**Implementation detail** 

One approach could be to iterate over the whole list decrementing 1 from their ticks member and call the callbacks of the ones with tick equal to 0. This would work, but performing asciimath:[O(N)] operations in an interrupt handler is not acceptable. 

We solve this by first keeping the queue ordered such that the function to be called the soonest will be the first element in the queue. On top of this, we change the meaning of the `sleep_ticks` member to mean how many ticks _after_ the sleeper in front of this sleeper. For instance, if we have 2 sleepers with 3 and 5 ticks in the beginning, we'll store them as 3 and 2 in the queue. The 2 means that 2 more ticks after the one with 3 ticks. 

This way, we only decrement the ticks of the first sleeper in the queue at any time. Once the first one reaches 0, we'll call all the functions with 0 ticks and remove them.
====

By far, the most common use case of an alarm is to put a thread to sleep for some time:

[source,cpp]
----
tos::this_thread::sleep_for(alarm, 5s);
----

`sleep_for` basically constructs an <<synchronization#events,event>>, and creates a `sleeper` with a function that simply notifies the said `event`. After setting the alarm, it then waits for the event to fire, thus putting the current thread to sleep for the given duration.