#define S_FRAME_SIZE 272

.macro	kernel_entry
    sub	sp, sp, #S_FRAME_SIZE
    stp	x0, x1, [sp, #16 * 0]
    stp	x2, x3, [sp, #16 * 1]
    stp	x4, x5, [sp, #16 * 2]
    stp	x6, x7, [sp, #16 * 3]
    stp	x8, x9, [sp, #16 * 4]
    stp	x10, x11, [sp, #16 * 5]
    stp	x12, x13, [sp, #16 * 6]
    stp	x14, x15, [sp, #16 * 7]
    stp	x16, x17, [sp, #16 * 8]
    stp	x18, x19, [sp, #16 * 9]
    stp	x20, x21, [sp, #16 * 10]
    stp	x22, x23, [sp, #16 * 11]
    stp	x24, x25, [sp, #16 * 12]
    stp	x26, x27, [sp, #16 * 13]
    stp	x28, x29, [sp, #16 * 14]
    str	x30, [sp, #16 * 15]
.endm

.macro	kernel_exit
    ldp	x0, x1, [sp, #16 * 0]
    ldp	x2, x3, [sp, #16 * 1]
    ldp	x4, x5, [sp, #16 * 2]
    ldp	x6, x7, [sp, #16 * 3]
    ldp	x8, x9, [sp, #16 * 4]
    ldp	x10, x11, [sp, #16 * 5]
    ldp	x12, x13, [sp, #16 * 6]
    ldp	x14, x15, [sp, #16 * 7]
    ldp	x16, x17, [sp, #16 * 8]
    ldp	x18, x19, [sp, #16 * 9]
    ldp	x20, x21, [sp, #16 * 10]
    ldp	x22, x23, [sp, #16 * 11]
    ldp	x24, x25, [sp, #16 * 12]
    ldp	x26, x27, [sp, #16 * 13]
    ldp	x28, x29, [sp, #16 * 14]
    ldr	x30, [sp, #16 * 15]
    add	sp, sp, #S_FRAME_SIZE
.endm

.extern exc_handler
.section ".text.vectors"
_handlers:
_sync_vec:
    // synchronous
    .align  7
    kernel_entry
    mov     x0, #0
    mrs     x1, esr_el1
    mrs     x2, elr_el1
    mrs     x3, spsr_el1
    mrs     x4, far_el1
    bl      exc_handler
    kernel_exit
    eret

_irq_vec:
    // IRQ
    .align  7
    kernel_entry
    mov     x0, #1
    mrs     x1, esr_el1
    mrs     x2, elr_el1
    mrs     x3, spsr_el1
    mrs     x4, far_el1
    bl      exc_handler
    kernel_exit
    eret

_fiq_vec:
    // FIQ
    .align  7
    kernel_entry
    mov     x0, #2
    mrs     x1, esr_el1
    mrs     x2, elr_el1
    mrs     x3, spsr_el1
    mrs     x4, far_el1
    bl      exc_handler
    kernel_exit
    eret

_serror_vec:
    // SError
    .align  7
    kernel_entry
    mov     x0, #3
    mrs     x1, esr_el1
    mrs     x2, elr_el1
    mrs     x3, spsr_el1
    mrs     x4, far_el1
    bl      exc_handler
    kernel_exit
    eret


.global _vectors
.align 11
_vectors:
    // synchronous
    .align  7
    b _sync_vec

    // IRQ
    .align  7
    b _irq_vec

    // FIQ
    .align  7
    b _fiq_vec

    // SError
    .align  7
    b _serror_vec

    // synchronous
    .align  7
    b _sync_vec

    // IRQ
    .align  7
    b _irq_vec

    // FIQ
    .align  7
    b _fiq_vec

    // SError
    .align  7
    b _serror_vec