= Get Started on STM32L4 Discovery Kit

Vendor page: https://www.st.com/en/evaluation-tools/b-l475e-iot01a.html

== Setup

. Download and install the arm toolchain.
.. Instructions are here: <<../toolchains/gnu-arm-none-eabi.adoc#Setup, Here>>
. You can now compile a tos firmware for the device, but you need OpenOCD
to program the firmware to the device.
.. Instructions to build OpenOCD are here: <<../general/openocd.adoc#Setup, Here>>

== Building and flashing a simple program

=== Generate the build system

. In `tos`, create a build directory for the board and go to it.
.. `mkdir build-stm32l4 && cd build-stm32l4`
. Generate the build for the specific CPU.
.. `cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DTOS_CPU=stm32/l4/75 ..`
.. You do not have to use `ninja`, but it is highly recommended.
.. The `CMAKE_BUILD_TYPE=MinSizeRel` option instructs CMake to
generate build commands with appropriate optimization flags.
.. The `TOS_CPU=stm32/l4/75` instructs our build system to configure
for the CPU on the board.

=== Compile the blink example

. In the build directory, just build the `blink` target.
.. `ninja blink`
. That's it! You should have the binary in `bin/blink`.

=== Program the binary to the board

Connect the board to your PC, and run the following command:

[source,sh]
----
/path/to/openocd/src/openocd                \
    -s /path/to/openocd/tcl                 \
    -f interface/stlink.cfg                 \ <1>
    -f target/stm32l4x.cfg                  \ <2>
    -c "program bin/blink verify reset exit"  <3>
----

<1> This line tells openocd to use the `stlink` interface, which
is the debugger found on the board.
<2> This line tells openocd that it will be programming a target
in the `stm32l4` family.
<3> This line instructs openocd to program the device with our
blink binary, verify the programming with a checksum and reset the
chip when programming is done and exit.

When the command finishes, the green LED on the board should be
blinking at 1 second intervals.