$lidlmeta:
  name: tos::services

system_status:
  type: service
  procedures:
    get_commit_hash:
      returns:
        - string_view
      parameters:
    get_build_id:
      returns:
        - string_view
      parameters:
    get_arch:
      returns:
        - string_view
      parameters:
