$lidlmeta:
  name: tos::services

service_info:
  type: structure
  members:
    port: u16
    module_hash: u32
    service_hash: u32

discovery:
  type: service
  procedures:
    service_count:
      returns: [i16]
      parameters: []
    services:
      returns:
        - name: vector
          parameters:
            - service_info
      parameters: []

system_status:
  type: service
  procedures:
    get_commit_hash:
      returns:
        - string_view
      parameters:
    get_build_id:
      returns:
        - string_view
      parameters:
    get_arch:
      returns:
        - string_view
      parameters:
