set(TOS_PLATFORM stm32_hal)
set(TOS_DRIVERS stm32_hal)
SET(LIBOPENCM_DEF STM32L0)
SET(TOS_CPU_ARCH cortex-m0plus)
set(TOS_DEF_STACK 512)
set(TOS_TOOLCHAIN stm32Toolchain)
set(HAL_NAME stm32l0xx)
set(COMPILE_FLAGS "-msoft-float")