= Tos

image::https://github.com/FatihBAKIR/tos/actions/workflows/build.yml/badge.svg[]

**tos** is a multitasking operating system for the Internet of Things. tos focuses on efficiency,
ease of programming and compile time safety features.

**tos** provides a modern programming environment even on extremely resource constrained environments.
It can work on boards with less than 1k of ram and 5k of program flash.
These numbers are not just the OS, it also includes an application.

== In a nutshell

- Cooperative multitasking kernel, with optional preemption.
- Efficient, zero overhead abstraction model.
- First class C++ support, with extensive standard library support.
- Written using modern programming practices with focus on
maintainability, safety and portability.
- A novel <<docs/contexts#, context>> mechanism to provide high level abstractions.
- Optional memory protection support on both high end MMUs and low end MPUs.
- Run the same C++20 program on an 8-bit AVR or a 64-bit aarch64 processor.
- Power efficient out of the box. **tos** is a tickless kernel, so it will always
sleep automatically when there isn't anything to run.

== Modern practices

**tos** follows modern software development practices, including:

. Stay up to date in terms of language and tools.
.. We use the most recent stable compilers, build tools etc.
. On every commit, a broad continuous integration suite runs automatically.
.. Every software target gets built for every hardware target.
.. All unit tests are checked
.. Benchmarks are collected for performance regressions
.. Final program sizes are collected for size regressions

The primary goal with these is to provide a programming environment familiar to experienced software
developers for them to easily transfer their skills to Internet of Things applications development.

== Supported Targets

**tos** is highly portable and supports new architectures witn only a handful of functions.

Besides bare metal targets, most of tos functionality can run in user space on other operating systems
for ease of development and program portability.

Full list of supported and tested targets <<docs/targets#, can be found here>>.

== Getting Started

There is a helper script to document and ease setting up an Ambience build environment.

The only dependencies of the script are GNU coreutils, bash, sed, and `dnf`, the Fedora package
manager. The only tested `dnf` version is 4.5.2.

To build and run the calc_test_deployment, run these commands as root on any machine with `dnf`
installed:

[source,bash]
----
wget https://raw.githubusercontent.com/MAYHEM-Lab/ambience/master/scripts/ambience-helpers.sh
chmod +x ambience-helpers.sh
mkdir build-env-directory
./ambience-helpers.sh bootstrap build-env-directory
./ambience-helpers.sh setup build-env-directory
./ambience-helpers.sh run-basic-calc build-env-directory
----

