set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86)

include(TosFunctions)

function(find_llvm_toolchain)
    set(SEARCH_DIRS ${TOOLCHAIN_HINTS})
    list(APPEND SEARCH_DIRS /opt/x-tools)
    list(APPEND SEARCH_DIRS C:/x-tools)
    list(APPEND SEARCH_DIRS C:/LLVM9)

    SUBDIRLIST(X_TOOLS_SUBS C:/x-tools)
    foreach(path ${X_TOOLS_SUBS})
        list(APPEND SEARCH_DIRS C:/x-tools/${path})
    endforeach()

    SUBDIRLIST(X_TOOLS_SUBS /opt/x-tools)
    foreach(path ${X_TOOLS_SUBS})
        list(APPEND SEARCH_DIRS /opt/x-tools/${path})
    endforeach()

    find_program(TOOLCHAIN_CXX_COMPILER 
        clang
        HINTS ${SEARCH_DIRS}
        PATH_SUFFIXES bin)
    set(TOOLCHAIN_CXX_COMPILER ${TOOLCHAIN_CXX_COMPILER} PARENT_SCOPE)
    set(TOOLCHAIN_C_COMPILER ${TOOLCHAIN_CXX_COMPILER} PARENT_SCOPE)
    set(TOOLCHAIN_ASM_COMPILER ${TOOLCHAIN_CXX_COMPILER} PARENT_SCOPE)
    
    find_program(TOOLCHAIN_LINKER 
        ld.lld
        HINTS ${SEARCH_DIRS}
        PATH_SUFFIXES bin)
    set(TOOLCHAIN_LINKER ${TOOLCHAIN_LINKER} PARENT_SCOPE)
endfunction()

find_llvm_toolchain()
SET(CMAKE_ASM_COMPILER ${TOOLCHAIN_ASM_COMPILER})
set(CMAKE_C_COMPILER ${TOOLCHAIN_C_COMPILER})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_CXX_COMPILER})
set(CMAKE_SIZE size CACHE STRING "CMAKE_SIZE")
set(CMAKE_OBJCOPY objcopy CACHE STRING "CMAKE_OBJCOPY")

set(CMAKE_LINKER ${TOOLCHAIN_LINKER})
set(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS) # this removed -rdynamic from linker output
set(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER> -o <TARGET> <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES>")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(X86_FLAGS "--target=aarch64 -nostdlib -fno-builtin")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${X86_FLAGS} --sysroot=.")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${X86_FLAGS} --sysroot=.")
set(CMAKE_ASM_FLAGS "${CMAKE_C_FLAGS} ${X86_FLAGS} --sysroot=.")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")

set(TOS_PROVIDE_LIBCXX ON)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}" CACHE STRING "CFLAGS")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" CACHE STRING "CXXFLAGS")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}" CACHE STRING "")

set(CMAKE_CXX_COMPILER ${CMAKE_CXX_COMPILER} CACHE STRING "CMAKE_CXX_COMPILER")
set(CMAKE_C_COMPILER ${CMAKE_C_COMPILER} CACHE STRING "CMAKE_C_COMPILER")
set(CMAKE_SIZE ${CMAKE_SIZE} CACHE STRING "CMAKE_SIZE")
set(CMAKE_LINKER ${CMAKE_LINKER} CACHE STRING "CMAKE_LINKER")
set(CMAKE_OBJCOPY "${CMAKE_OBJCOPY}" CACHE STRING "OBJCOPY")
set(CMAKE_LINKER "${CMAKE_LINKER}" CACHE STRING "CMAKE_LINKER")
set(CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_CXX_LINK_EXECUTABLE}" CACHE STRING "CMAKE_CXX_LINK_EXECUTABLE")
