include(ArmToolchain)

set(TOS_NRF52_FLAGS "-mcpu=${TOS_CPU_ARCH} -DFLOAT_ABI_HARD -DCONFIG_GPIO_AS_PINRESET -D${NRFSDK_DEF}")
set(TOS_NRF52_FLAGS "${TOS_NRF52_FLAGS} -DNRF52_PAN_74 -mthumb -DNRF_SD_BLE_API_VERSION=6 -D${NRF52_SOFTDEV} -DSOFTDEVICE_PRESENT")
set(TOS_NRF52_FLAGS "${TOS_NRF52_FLAGS} -DSWI_DISABLE0 -mabi=aapcs -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fno-builtin -fshort-enums")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${TOS_NRF52_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TOS_NRF52_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "-Wl,--gc-sections -Xlinker -Map=output.map -fno-threadsafe-statics ${TOS_NRF52_FLAGS}")

SET(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>")
SET(CMAKE_C_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>")
SET(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>")
SET(CMAKE_CXX_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}" CACHE STRING "CFLAGS")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" CACHE STRING "CXXFLAGS")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}" CACHE STRING "")

set(SDK_ROOT /opt/x-tools/nRF5_SDK_15.3.0_59ac345)

include_directories(SYSTEM ${SDK_ROOT}/integration/nrfx)

include_directories(SYSTEM ${SDK_ROOT}/modules/nrfx)
include_directories(SYSTEM ${SDK_ROOT}/modules/nrfx/mdk/)
include_directories(SYSTEM ${SDK_ROOT}/modules/nrfx/hal)
include_directories(SYSTEM ${SDK_ROOT}/modules/nrfx/drivers/include)

include_directories(SYSTEM ${SDK_ROOT}/components/toolchain/cmsis/include/)
include_directories(SYSTEM ${SDK_ROOT}/components/libraries/delay)
include_directories(SYSTEM ${SDK_ROOT}/components/libraries/log)
include_directories(SYSTEM ${SDK_ROOT}/components/libraries/timer)
include_directories(SYSTEM ${SDK_ROOT}/components/libraries/atomic)
include_directories(SYSTEM ${SDK_ROOT}/components/libraries/atomic_flags)
include_directories(SYSTEM ${SDK_ROOT}/components/libraries/strerror)
include_directories(SYSTEM ${SDK_ROOT}/components/libraries/log/src)
include_directories(SYSTEM ${SDK_ROOT}/components/libraries/experimental_section_vars)
include_directories(SYSTEM ${SDK_ROOT}/components/libraries/util)
include_directories(SYSTEM ${SDK_ROOT}/components/ble)
include_directories(SYSTEM ${SDK_ROOT}/components/ble/common)
include_directories(SYSTEM ${SDK_ROOT}/components/ble/ble_link_ctx_manager)
include_directories(SYSTEM ${SDK_ROOT}/components/ble/nrf_ble_gatt)
include_directories(SYSTEM ${SDK_ROOT}/components/ble/ble_advertising)
include_directories(SYSTEM ${SDK_ROOT}/components/ble/nrf_ble_qwr)
include_directories(SYSTEM ${SDK_ROOT}/components/ble/ble_services/ble_nus)
#include_directories(${SDK_ROOT}/components/drivers_nrf/nrf_soc_nosd)
message(STATUS ${NRF52_SOFTDEV})
if (${NRF52_SOFTDEV} MATCHES "S140")
    include_directories(SYSTEM ${SDK_ROOT}/components/softdevice/s140/headers)
endif()
if (${NRF52_SOFTDEV} MATCHES "S132")
    include_directories(SYSTEM ${SDK_ROOT}/components/softdevice/s132/headers)
endif()
include_directories(SYSTEM ${SDK_ROOT}/components/softdevice/mbr/${NRF52_NAME}/headers)
include_directories(SYSTEM ${SDK_ROOT}/components/softdevice/common)
