include(ArmToolchain)

set(CMAKE_ASM_COMPILER_TARGET "armv7-none-eabi")
set(CMAKE_CXX_COMPILER_TARGET "armv7-none-eabi")
set(CMAKE_C_COMPILER_TARGET "armv7-none-eabi")

set(TOS_EXTRA_FLAGS "-mcpu=${TOS_CPU_ARCH} -march=armv7e-m -mthumb -fno-builtin -fshort-enums -g3 -Dgcc -DNORTOS_SUPPORT")
set(TOS_EXTRA_FLAGS "${TOS_EXTRA_FLAGS} -nostartfiles -mabi=aapcs ${COMPILE_FLAGS} -eresetISR -DDeviceFamily_CC3220")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${TOS_EXTRA_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TOS_EXTRA_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${TOS_EXTRA_FLAGS}")

SET(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>")
SET(CMAKE_C_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>")
SET(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>")
SET(CMAKE_CXX_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}" CACHE STRING "CFLAGS")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" CACHE STRING "CXXFLAGS")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}" CACHE STRING "")
