name: build

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y cmake wget xz-utils ninja-build tar gcc-11 g++-11 libboost-all-dev ccache

    - name: Cache LLVM
      id: cache-llvm
      uses: FatihBAKIR/cache@v2
      with:
        path: /opt/llvm
        key: ${{ runner.os }}-llvm-14-b

    - name: Cache CCache
      id: cache-ccache-dir
      uses: FatihBAKIR/cache@v2
      with:
        path: /home/runner/.ccache
        key: ${{ runner.os }}-ccache-0

    - name: Download LLVM
      if: steps.cache-llvm.outputs.cache-hit != 'true'
      run: >
        wget http://build.a6e.org/clang-14-fedora.tar.gz &&
        sudo mkdir /opt/llvm &&
        sudo tar xf clang-14-fedora.tar.gz -C /opt/llvm

    - name: Download lidlc
      run: wget http://cs.ucsb.edu/~bakir/lidlc && chmod +x lidlc && sudo mv lidlc /usr/local/bin/

    - uses: FatihBAKIR/checkout@v2

    - name: Create hosted debug build dir
      run: mkdir /tmp/cmake-build-debug

    - name: Generate hosted debug build
      run: >
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DTOS_BOARD=hosted
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
        $GITHUB_WORKSPACE
      working-directory: /tmp/cmake-build-debug
      env:
        CC: gcc-11
        CXX: g++-11

    - name: Build hosted debug
      run: ninja
      working-directory: /tmp/cmake-build-debug

    - name: Run tests
      run: ctest --rerun-failed --output-on-failure
      working-directory: /tmp/cmake-build-debug

    - name: Create amd64 user build dir
      run: mkdir /tmp/cmake-build-barex64-user

    - name: Generate amd64 user build
      run: >
        cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DTOS_CPU=x86_64/ae_user -DENABLE_LTO=ON
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DBUILD_USER_SPACE=ON
        $GITHUB_WORKSPACE
      working-directory: /tmp/cmake-build-barex64-user

    - name: Create amd64 build dir
      run: mkdir /tmp/cmake-build-barex64

    - name: Generate amd64 build
      run: >
        cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DTOS_BOARD=x86_64_pc -DENABLE_LTO=ON
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
        $GITHUB_WORKSPACE
      working-directory: /tmp/cmake-build-barex64

    - name: Build amd64
      run: ninja
      working-directory: /tmp/cmake-build-barex64

    - name: Create raspi3 build dir
      run: mkdir /tmp/cmake-build-raspi3

    - name: Generate raspi3 build
      run: >
        cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DTOS_CPU=raspi/3 -DENABLE_LTO=ON
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
        $GITHUB_WORKSPACE
      working-directory: /tmp/cmake-build-raspi3

    - name: Build raspi3
      run: ninja
      working-directory: /tmp/cmake-build-raspi3
