# This is a basic workflow to help you get started with Actions

name: tosdoc

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y ruby python3-pip ninja-build graphviz
    
    - name: Install asciidoctor
      run: sudo gem install asciidoctor asciidoctor-diagram

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: FatihBAKIR/checkout@v2
      
    - name: Echo workspace
      run: echo $GITHUB_WORKSPACE; ls $GITHUB_WORKSPACE
    
    - name: Install requirements
      run: pip3 install -r $GITHUB_WORKSPACE/tools/tosdoc/requirements.txt

    - name: Create build dir
      run: mkdir /tmp/docs
    
    - name: Generate
      run: python3 $GITHUB_WORKSPACE/tools/tosdoc/tosdoc.py $GITHUB_WORKSPACE
      working-directory: /tmp/docs
      
    - name: Build
      run: ninja
      working-directory: /tmp/docs
      
    - name: Upload docs
      uses: FatihBAKIR/upload-artifact@v2
      with:
        name: tosdoc
        path: /tmp/docs/tosdoc.tar.gz
        
    - name: Setup key
      run: echo "$DOCS_DEPLOY_KEY" > /tmp/deploykey
      env:
        DOCS_DEPLOY_KEY: ${{ secrets.DOCS_DEPLOY_KEY }}
        
    - name: Deploy
      run: cat /tmp/deploykey && chmod 600 /tmp/deploykey && scp -i /tmp/deploykey /tmp/docs fatih@docs.a6e.org:/home/fatih/docs.a6e.org/www/$GITHUB_SHA
