# This is a basic workflow to help you get started with Actions

name: tosdoc

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install ruby
      run: sudo apt-get install -y ruby
    
    - name: Install asciidoctor
      run: sudo gem install asciidoctor
    
    - name: Install python
      run: sudo apt-get install -y python3-pip

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: FatihBAKIR/checkout@v2
      
    - name: Echo workspace
      run: echo $GITHUB_WORKSPACE; ls $GITHUB_WORKSPACE
    
    - name: Install requirements
      run: pip3 install -r $GITHUB_WORKSPACE/tools/tosdoc/requirements.txt

    - name: Create build dir
      run: mkdir /tmp/docs
    
    - name: Generate
      run: python3 $GITHUB_WORKSPACE/tools/tosdoc/tosdoc.py $GITHUB_WORKSPACE
      working-directory: /tmp/docs
      
    - name: Build
      run: ninja
